{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2a357db6-4901-4802-989d-4e04298a7702",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pygame\n",
    "import random\n",
    "import math\n",
    "\n",
    "# ---------------- Config ----------------\n",
    "WORLD_WIDTH, WORLD_HEIGHT = 1600, 900\n",
    "DT_S = 0.05\n",
    "NETWORK_RADIUS = 350.0\n",
    "SAFE_DISTANCE = 250.0\n",
    "SENSOR_RANGE = 400.0\n",
    "ROAD_Y = WORLD_HEIGHT // 2\n",
    "CAR_LENGTH = 40.0\n",
    "\n",
    "# Colors\n",
    "COLOR_BG = (24, 28, 36)\n",
    "COLOR_ROAD = (50, 55, 65)\n",
    "COLOR_CAR = (90, 200, 255)\n",
    "COLOR_AMBULANCE = (255, 255, 255)\n",
    "COLOR_BLOCK = (180, 180, 180)\n",
    "\n",
    "# ---------------- Vehicle ----------------\n",
    "class Vehicle:\n",
    "    def __init__(self, x, y, speed, desired_speed, is_ambulance=False):\n",
    "        self.x = x\n",
    "        self.y = y\n",
    "        self.speed = speed\n",
    "        self.desired_speed = desired_speed\n",
    "        self.base_desired_speed = desired_speed\n",
    "        self.accel_mps2 = 0.0\n",
    "        self.is_ambulance = is_ambulance\n",
    "        self.hazard_ahead = None\n",
    "        self.target_speed = desired_speed\n",
    "        self.flash_timer = 0\n",
    "        self.flash = False\n",
    "        self.side_offset = 0  # for giving way\n",
    "        self.lane_y = y\n",
    "\n",
    "        if not is_ambulance:\n",
    "            self.generate_car_style()\n",
    "        else:\n",
    "            self.body_color = COLOR_AMBULANCE\n",
    "            self.stripe_type = \"ambulance\"\n",
    "\n",
    "    def generate_car_style(self):\n",
    "        colors = [(255, 50, 50), (50, 100, 255), (255, 220, 0), (50, 200, 50),\n",
    "                  (255, 100, 200), (150, 50, 200), (255, 140, 0), (0, 200, 200),\n",
    "                  (240, 240, 240), (40, 40, 40)]\n",
    "        self.body_color = random.choice(colors)\n",
    "        self.stripe_type = random.choice([None, \"racing\", \"horizontal\", \"number\"])\n",
    "        if self.stripe_type == \"number\":\n",
    "            self.number = random.randint(1, 99)\n",
    "\n",
    "    def step(self, dt):\n",
    "        # Smooth speed adjustment\n",
    "        delta = self.target_speed - self.speed\n",
    "        accel_limit = 2.5 if delta > 0 else -6.0\n",
    "        self.accel_mps2 = max(-6.0, min(2.5, delta / dt))\n",
    "        self.speed += self.accel_mps2 * dt\n",
    "        self.speed = max(0, self.speed)\n",
    "\n",
    "        # Update ambulance flashing\n",
    "        if self.is_ambulance:\n",
    "            self.flash_timer += 1\n",
    "            if self.flash_timer % 15 == 0:\n",
    "                self.flash = not self.flash\n",
    "\n",
    "        # Smooth return of y position if moved aside\n",
    "        if not self.is_ambulance:\n",
    "            self.y += (self.lane_y + self.side_offset - self.y) * 0.1\n",
    "\n",
    "        self.x += self.speed * dt\n",
    "        if self.x > WORLD_WIDTH + 50:\n",
    "            self.x = -300\n",
    "            self.speed = min(self.speed, 15.0)\n",
    "\n",
    "# ---------------- Simulation ----------------\n",
    "class Simulation:\n",
    "    def __init__(self, scenario=\"ambulance\"):\n",
    "        self.scenario = scenario\n",
    "        self.vehicles = []\n",
    "        self.time_s = 0.0\n",
    "        self.create_vehicles()\n",
    "\n",
    "    def create_vehicles(self):\n",
    "        lanes = [ROAD_Y - 60, ROAD_Y, ROAD_Y + 60]\n",
    "\n",
    "        # Create normal cars\n",
    "        for i in range(15):\n",
    "            lane = random.choice(lanes)\n",
    "            x_pos = (i * 150) % WORLD_WIDTH\n",
    "            v = Vehicle(x=x_pos, y=lane,\n",
    "                        speed=random.uniform(18, 23),\n",
    "                        desired_speed=25.0)\n",
    "            self.vehicles.append(v)\n",
    "\n",
    "        # Add ambulance\n",
    "        if self.scenario == \"ambulance\":\n",
    "            self.ambulance = Vehicle(x=-200, y=ROAD_Y, speed=25, desired_speed=35, is_ambulance=True)\n",
    "            self.vehicles.append(self.ambulance)\n",
    "        else:\n",
    "            self.ambulance = None\n",
    "\n",
    "    def step(self):\n",
    "        self.vehicles.sort(key=lambda v: v.x)\n",
    "\n",
    "        ambulance = self.ambulance if self.ambulance else None\n",
    "\n",
    "        for v in self.vehicles:\n",
    "            # Normal behavior for cars\n",
    "            v.target_speed = v.base_desired_speed\n",
    "\n",
    "            if ambulance and not v.is_ambulance:\n",
    "                # Distance to ambulance behind\n",
    "                dx = ambulance.x - v.x\n",
    "                dy = abs(ambulance.y - v.y)\n",
    "                if -250 < dx < 200 and dy < 80:\n",
    "                    # Give way smoothly\n",
    "                    if v.y < ROAD_Y:\n",
    "                        v.side_offset = -30\n",
    "                    else:\n",
    "                        v.side_offset = 30\n",
    "                    v.target_speed = v.base_desired_speed * 0.8  # slow slightly\n",
    "                else:\n",
    "                    v.side_offset *= 0.95  # return slowly\n",
    "\n",
    "            v.step(DT_S)\n",
    "\n",
    "        # Move ambulance\n",
    "        if ambulance:\n",
    "            ambulance.step(DT_S)\n",
    "\n",
    "        # Prevent overlap in same lane\n",
    "        for i, v1 in enumerate(self.vehicles):\n",
    "            for v2 in self.vehicles[i+1:]:\n",
    "                if abs(v1.y - v2.y) < 20:\n",
    "                    dist = abs(v1.x - v2.x)\n",
    "                    if dist < CAR_LENGTH + 5:\n",
    "                        overlap = (CAR_LENGTH + 5) - dist\n",
    "                        if v1.x > v2.x:\n",
    "                            v1.x += overlap / 2\n",
    "                            v2.x -= overlap / 2\n",
    "                        else:\n",
    "                            v2.x += overlap / 2\n",
    "                            v1.x -= overlap / 2\n",
    "\n",
    "        self.time_s += DT_S\n",
    "\n",
    "# ---------------- Visualization ----------------\n",
    "class Visual:\n",
    "    def __init__(self, sim, fps=30):\n",
    "        pygame.init()\n",
    "        self.screen = pygame.display.set_mode((WORLD_WIDTH, WORLD_HEIGHT))\n",
    "        pygame.display.set_caption(\"Ambulance Scenario\")\n",
    "        self.clock = pygame.time.Clock()\n",
    "        self.sim = sim\n",
    "        self.font = pygame.font.SysFont(\"Arial\", 18)\n",
    "        self.fps = fps\n",
    "\n",
    "    def draw(self):\n",
    "        self.screen.fill(COLOR_BG)\n",
    "        pygame.draw.rect(self.screen, COLOR_ROAD, (0, ROAD_Y - 120, WORLD_WIDTH, 240))\n",
    "\n",
    "        # Lane dividers\n",
    "        for y_offset in [-60, 60]:\n",
    "            for x in range(0, WORLD_WIDTH, 40):\n",
    "                pygame.draw.line(self.screen, (80, 80, 80),\n",
    "                                 (x, ROAD_Y + y_offset),\n",
    "                                 (x + 20, ROAD_Y + y_offset), 2)\n",
    "\n",
    "        # Draw vehicles\n",
    "        for v in self.sim.vehicles:\n",
    "            car_x = int(v.x - CAR_LENGTH / 2)\n",
    "            car_y = int(v.y - 10)\n",
    "            car_w = int(CAR_LENGTH)\n",
    "            car_h = 20\n",
    "\n",
    "            pygame.draw.rect(self.screen, v.body_color, (car_x, car_y, car_w, car_h))\n",
    "            pygame.draw.rect(self.screen, (0, 0, 0), (car_x, car_y, car_w, car_h), 2)\n",
    "\n",
    "            # Ambulance flashing\n",
    "            if v.is_ambulance and v.flash:\n",
    "                pygame.draw.rect(self.screen, (255, 0, 0), (car_x + 5, car_y - 5, 10, 5))\n",
    "                pygame.draw.rect(self.screen, (0, 0, 255), (car_x + car_w - 15, car_y - 5, 10, 5))\n",
    "\n",
    "        txt = self.font.render(f\"Scenario: {self.sim.scenario} | Time: {self.sim.time_s:.1f}s\", True, (220, 230, 245))\n",
    "        self.screen.blit(txt, (10, 10))\n",
    "\n",
    "    def loop(self, duration_s=60):\n",
    "        end_t = self.sim.time_s + duration_s\n",
    "        running = True\n",
    "        while running and self.sim.time_s < end_t:\n",
    "            for event in pygame.event.get():\n",
    "                if event.type == pygame.QUIT:\n",
    "                    running = False\n",
    "\n",
    "            self.sim.step()\n",
    "            self.draw()\n",
    "            pygame.display.flip()\n",
    "            self.clock.tick(self.fps)\n",
    "\n",
    "        pygame.quit()\n",
    "\n",
    "# ---------------- Run ----------------\n",
    "sim = Simulation(scenario=\"ambulance\")\n",
    "vis = Visual(sim)\n",
    "vis.loop(duration_s=60)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "074cde5b-264b-4ef7-a9e0-dc49c4a00faa",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
