@echo off
REM V2V Node Key Generation Script (Windows Batch Version)
REM Usage: gen_keys.bat <node_name>
REM Example: gen_keys.bat car1

if "%1"=="" (
    echo Usage: %0 ^<node_name^>
    echo Example: %0 car1
    exit /b 1
)

set NODE_NAME=%1

REM Create keys directory if it doesn't exist
if not exist "keys" (
    mkdir keys
    echo Created ./keys/ directory
)

REM Check if OpenSSL is available
where openssl >nul 2>&1
if %errorlevel% neq 0 (
    echo Error: OpenSSL is not installed or not in PATH
    echo.
    echo To install OpenSSL on Windows:
    echo 1. Download from: https://slproweb.com/products/Win32OpenSSL.html
    echo 2. Or use Chocolatey: choco install openssl
    echo 3. Or use Git Bash which includes OpenSSL
    echo.
    echo For now, creating placeholder key files...
    goto :create_placeholder
)

REM Generate private key using secp256r1 (prime256v1) curve
echo Generating ECDSA private key for %NODE_NAME%...
openssl ecparam -genkey -name prime256v1 -noout -out "keys\%NODE_NAME%_priv.pem"

if %errorlevel% neq 0 (
    echo Error: Failed to generate private key
    exit /b 1
)

REM Generate public key from private key
echo Generating public key for %NODE_NAME%...
openssl ec -in "keys\%NODE_NAME%_priv.pem" -pubout -out "keys\%NODE_NAME%_pub.pem"

if %errorlevel% neq 0 (
    echo Error: Failed to generate public key
    del "keys\%NODE_NAME%_priv.pem" 2>nul
    exit /b 1
)

echo Keys generated for %NODE_NAME% in ./keys/
echo   Private key: keys\%NODE_NAME%_priv.pem
echo   Public key:  keys\%NODE_NAME%_pub.pem
echo.
echo Key details:
openssl ec -in "keys\%NODE_NAME%_priv.pem" -text -noout | findstr /C:"Private-Key" /C:"ASN1 OID" /C:"NIST CURVE"
goto :end

:create_placeholder
echo Creating placeholder key files for %NODE_NAME%...
echo # Placeholder private key for %NODE_NAME% > "keys\%NODE_NAME%_priv.pem"
echo # Generated by gen_keys.bat without OpenSSL >> "keys\%NODE_NAME%_priv.pem"
echo # Install OpenSSL to generate real ECDSA keys >> "keys\%NODE_NAME%_priv.pem"

echo # Placeholder public key for %NODE_NAME% > "keys\%NODE_NAME%_pub.pem"
echo # Generated by gen_keys.bat without OpenSSL >> "keys\%NODE_NAME%_pub.pem"
echo # Install OpenSSL to generate real ECDSA keys >> "keys\%NODE_NAME%_pub.pem"

echo Placeholder keys created for %NODE_NAME% in ./keys/
echo   Private key: keys\%NODE_NAME%_priv.pem
echo   Public key:  keys\%NODE_NAME%_pub.pem
echo.
echo Note: These are placeholder files. Install OpenSSL to generate real ECDSA keys.

:end
